import jsPDF from 'jspdf';
import type { AllocationPlan } from '../types';

export async function exportPassportPdf(plan: AllocationPlan, hash: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Passport', 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('RWA Cash Terminal — Institutional Compliance Framework', 14, y);
  y += 5;
  doc.text(`Generated: ${new Date().toISOString()}`, 14, y);
  y += 12;

  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Composite Risk Score', 14, y);
  y += 7;
  doc.setFontSize(28);
  doc.text(`${plan.passport.score}/100`, 14, y);
  doc.setFontSize(14);
  doc.text(`Grade: ${plan.passport.grade}`, 80, y);
  y += 14;

  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Risk Dimensions', 14, y);
  y += 8;

  const dimensions: [string, number][] = [
    ['Smart Contract', plan.passport.radarData.contract],
    ['Liquidity / Exit', plan.passport.radarData.liquidity],
    ['Oracle / Pricing', plan.passport.radarData.oracle],
    ['Market', plan.passport.radarData.market],
    ['Operational', plan.passport.radarData.operational],
  ];

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  dimensions.forEach(([name, value]) => {
    doc.setTextColor(80);
    doc.text(String(name), 14, y);
    doc.setTextColor(0);
    doc.setFont('courier', 'bold');
    doc.text(`${value}/100`, 100, y);
    doc.setFont('helvetica', 'normal');
    y += 6;
  });

  if (!plan.passport.riskDimensionsSource || plan.passport.riskDimensionsSource === 'demo_defaults') {
    y += 2;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(180, 120, 0);
    doc.text('\u26A0 Risk dimensions use demo defaults \u2014 not sourced from protocol or on-chain risk feeds.', 14, y);
    doc.setTextColor(0);
    y += 8;
  } else {
    y += 6;
  }

  doc.setDrawColor(200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  if (plan.passport.explanations && plan.passport.explanations.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Allocation Rationale', 14, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60);
    plan.passport.explanations.forEach((exp, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${exp}`, pageWidth - 28);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 2;
    });
    y += 6;

    doc.setDrawColor(200);
    doc.line(14, y, pageWidth - 14, y);
    y += 8;
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Passport Hash', 14, y);
  y += 7;

  doc.setFontSize(8);
  doc.setFont('courier', 'normal');
  doc.setTextColor(60);
  const hashLines = doc.splitTextToSize(hash || 'N/A', pageWidth - 28);
  doc.text(hashLines, 14, y);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150);
  doc.text(
    'Generated by RWA Cash Terminal • Ethereum Sepolia',
    14,
    doc.internal.pageSize.getHeight() - 10,
  );

  doc.save(`risk-passport-${new Date().toISOString().slice(0, 10)}.pdf`);
}
